name: PR Approval Slack Notification

on:
  push:  # Trigger on any push to any branch

env:
  REQUIRED_APPROVALS: 2  # Set the required number of approvals
  GITHUB_TO_SLACK_MAP: '{"Rspoon3": "U04APJ20ZFY"}'  # Map as a JSON string

jobs:
  notify-on-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Check for approvals with debug logs and pending reviewer handling
        id: approval_check
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const approvalsLength = 2;

            // Parse GitHub to Slack mapping from the environment variable
            const githubToSlackMap = JSON.parse(process.env.GITHUB_TO_SLACK_MAP);

            // Get corresponding Slack ID
            const slackUser = githubToSlackMap["Rspoon3"] || null;

            if (!slackUser) {
              console.log(`No Slack mapping found for GitHub user: Rspoon3`);
              return { approvals: 0 };
            }

            // Log the number of current approvals
            console.log(`Number of current approvals: ${approvalsLength}`);

            // Return approvals and slackUser to be used in the next steps
            return { approvals: approvalsLength, slackUser };

      - name: Exit if approval count is not met
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const approvals = parseInt(steps.approval_check.outputs.approvals);
            const required = parseInt(process.env.REQUIRED_APPROVALS);
            const slackUser = steps.approval_check.outputs.slackUser;

            console.log(`Approvals: ${approvals}, Required: ${required}`);
            console.log(`Slack User: ${slackUser}`);

            if (approvals !== required) {
              console.log("Approval count not met, stopping action.");
              process.exit(1);  // Exit if approvals do not match required
            } else {
              console.log("Approval count met.");
            }

      - name: Send message to Slack
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const approvals = parseInt(steps.approval_check.outputs.approvals);
            const required = parseInt(process.env.REQUIRED_APPROVALS);
            const slackUser = steps.approval_check.outputs.slackUser;

            console.log(`Approvals slack: ${approvals}, Required: ${required}`);
            console.log(`Slack User slack: ${slackUser}`);

            if (approvals !== required) {
              console.log("Slack approval count not met, stopping action.");
              process.exit(1);
            } else {
              console.log("Slack approval count met.");
            }