name: PR Approval Slack Notification

on:
  push:  # Trigger on any push to any branch

env:
  REQUIRED_APPROVALS: 2  # Set the required number of approvals
  GITHUB_TO_SLACK_MAP: '{"Rspoon3": "U04APJ20ZFY"}'  # Map as a JSON string

jobs:
  notify-on-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Check for approvals with debug logs and pending reviewer handling
        id: approval_check
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string  # Ensure output is in string format
          retries: 3  # Retry the action 3 times if it fails
          retry-exempt-status-codes: 400,401,403  # Do not retry if these status codes are encountered
          script: |
            const approvalsLength = 2;

            // Parse GitHub to Slack mapping from the environment variable
            const githubToSlackMap = JSON.parse(process.env.GITHUB_TO_SLACK_MAP);

            // Get corresponding Slack ID
            const slackUser = githubToSlackMap["Rspoon3"] || null;

            if (!slackUser) {
              console.log(`No Slack mapping found for GitHub user: ${prCreator}`);
              return { approvals: 0 };
            }

            // Log the number of current approvals
            console.log(`Number of current approvals: ${approvalsLength}`);

            // Set the outputs for next steps
            core.setOutput("approvals", approvalsLength);
            core.setOutput("slackUser", slackUser);

      - name: Exit if approval count is not met
        run: |
          approvals=${{ steps.approval_check.outputs.approvals }}
          slackUser=${{ steps.approval_check.outputs.slackUser }}
          required=${{ env.REQUIRED_APPROVALS }}

          echo "Approvals: $approvals, Required: $required"
          echo "slackUser: $slackUser, Required: $required"

          if [ "$approvals" -ne "$required" ]; then
            echo "Approval count not met, stopping action."
            exit 1
          else
            echo "Approval count met."
          fi